spring.application.name=Peertube-Miner
server.port=8082

Peertube-Miner.baseuri = https://peertube.tv/api/v1

Peertube-Miner.maxVideos = 10
Peertube-Miner.maxComments = 10

videominer.uri = http://localhost:8080/videominer/channels